name: CI

on: [push]

jobs:
  lint_and_format:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
          cache: "npm"
      - run: npm ci
      - name: Format
        run: npm run format
      - name: Lint
        run: npm run lint

  test:
    strategy:
      matrix:
        os: [ubuntu-slim]
        node-version: ['22.x', '24.x', '26.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run with Node v${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Versions
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
      - run: npm ci
      - run: npm test
